#!/usr/bin/env python
"""Launch the PAIRS Inspection panel as a standalone rqt window.

  rosrun inspection_core inspection_gui        # or via launch/inspection.launch
"""
import sys
from rqt_gui.main import Main


def main():
    return Main().main(sys.argv, standalone='inspection_core')


if __name__ == '__main__':
    sys.exit(main())
