#!/usr/bin/env python3
"""Generate the semantic 3D BIN map (warehouse_bins.yaml) for the inspection core.

Reconciled with BOTH the Gazebo world (6 racks, anchor tags 101-106) AND the live
relative navigation in inspection_core's rqt panel (inspection_panel.py) /
relative_navigator.py, so the *static map* and the *in-flight motion* agree exactly.

Geometry (from models/warehouse_rack/generate_rack.py + worlds/warehouse.world):
  * 3 columns (bays) per rack at world x in {-2.70, 0.00, 2.70}
  * 6 levels; the label/tag centre is at z = 1.1 + (level-1)*1.20  -> {1.1 .. 7.1}
    (the deck sits 0.6 m lower; the label is read at tag height, not deck height)
  * 6 racks, anchor tags 101-106, facing the aisle. dir=+1 -> front faces -y;
    dir=-1 -> front faces +y. The drone reads each label from a standoff pose
    STANDOFF_DEPTH into the aisle, yaw square to the face.

Each BIN stores the DRONE STANDOFF POSE (the actionable quantity for go-to-BIN /
zig-zag navigation), the label pose on the face, the rack's anchor tag, and a SAP
slot. 6 racks x 3 columns x 6 levels = 108 BINs. Re-run after a site survey.

    python3 generate_bin_map.py > warehouse_bins.yaml
"""

BAY_WIDTH      = 2.70
LEVEL_HEIGHT   = 1.20
COL_X          = (-2.70, 0.00, 2.70)   # bay-centre x (world) for columns 1,2,3
LABEL_Z        = tuple(round(1.1 + i * LEVEL_HEIGHT, 2) for i in range(6))  # 1.1 .. 7.1
FACE_OFFSET    = 0.40    # rack front face / label, this far (y) from the rack centre-line
STANDOFF_DEPTH = 1.50    # drone stands this far (y) from the rack centre-line, into the aisle

# rack -> (anchor tag id, rack centre-line world y, facing dir). Matches racks_config
# in inspection_core/inspection_panel.py and relative_navigator.py.
RACKS = {
    1: {"tag": 101, "y": 6.3,  "dir": 1},
    2: {"tag": 102, "y": 3.7,  "dir": -1},
    3: {"tag": 103, "y": 1.3,  "dir": 1},
    4: {"tag": 104, "y": -1.3, "dir": -1},
    5: {"tag": 105, "y": -3.7, "dir": 1},
    6: {"tag": 106, "y": -6.3, "dir": -1},
}
RACK_LETTER = {1: "A", 2: "B", 3: "C", 4: "D", 5: "E", 6: "F"}


def main():
    print("# AUTO-GENERATED by generate_bin_map.py - do not edit by hand.")
    print("# Semantic 3D BIN map: 6 racks x 3 columns x 6 levels = 108 BINs.")
    print("# BIN id = R<rack>B<nn>, bins 1..18 per rack with col=(bin-1)%3, level=(bin-1)//3+1")
    print("# (same numbering as the zig-zag navigation). Poses in the world/mapping_origin")
    print("# frame [m], yaw [rad]. standoff_pose is the drone pose that reads the label.")
    print("bins:")
    for r, cfg in RACKS.items():
        ry, d = cfg["y"], cfg["dir"]
        face_y     = round(ry - FACE_OFFSET * d, 3)       # label on the front face
        standoff_y = round(ry - STANDOFF_DEPTH * d, 3)    # drone hovers here, in the aisle
        yaw        = round(1.5708 * d, 4)                  # square to the face (faces the rack)
        for b in range(1, 19):
            col = (b - 1) % 3
            level = (b - 1) // 3 + 1
            x = COL_X[col]
            z = LABEL_Z[level - 1]
            print(f"  - id: R{r}B{b:02d}")
            print(f"    rack: {r}")
            print(f"    column: {col + 1}")
            print(f"    level: {level}")
            print(f"    tag_id: {cfg['tag']}")
            print(f"    bin_pose:      {{x: {x:.2f}, y: {face_y:.2f}, z: {z:.2f}}}            # label centre on the rack face")
            print(f"    standoff_pose: {{x: {x:.2f}, y: {standoff_y:.2f}, z: {z:.2f}, yaw: {yaw}}}  # drone pose to read it")
            print(f"    sap_slot: RACK-{RACK_LETTER[r]}/{col + 1:02d}/{level:02d}")


if __name__ == "__main__":
    main()
