#!/usr/bin/env python3
"""Generate the semantic BIN map (warehouse_bins.yaml) for the inspection core.

Keyed to the simulation rack in inspection_sim/gazebo_sim (left rack, front face at
y = +0.8, aisle centerline at y = 0). Each BIN stores the DRONE STANDOFF POSE required
to read its label fronto-parallel — that is the actionable quantity for go-to-BIN
navigation. Re-run after a site survey to match measured rack geometry.

    python3 generate_bin_map.py > warehouse_bins.yaml
"""

# --- rack geometry (must match models/warehouse_rack/generate_rack.py) ----------
COLS = [1, 2, 3]                       # columns (bays)
COL_X = {1: -2.70, 2: 0.00, 3: 2.70}   # bay-center x in the world frame
LEVELS = [1, 2, 3, 4, 5, 6]            # storage levels
LEVEL_Z = {1: 0.5, 2: 1.7, 3: 2.9, 4: 4.1, 5: 5.3, 6: 6.5}
RACK_FACE_Y = 0.80                     # left-rack aisle-facing face
STANDOFF_D = 0.80                      # drone stands this far from the face (at y=0, the aisle centerline)
STANDOFF_YAW = 1.5708                  # +90 deg: face +y toward the left rack
COL_TAG = {1: 1, 2: 2, 3: 3}           # nearest surveyed AprilTag anchor per column


def main():
    print("# AUTO-GENERATED by generate_bin_map.py — do not edit by hand.")
    print("# Semantic BIN map: (column,level) -> drone standoff pose to read the label.")
    print("# pose frames are the world/mapping_origin frame [m], yaw [rad].")
    print("bins:")
    for c in COLS:
        for l in LEVELS:
            x = COL_X[c]
            z = LEVEL_Z[l]
            print(f"  - id: C{c}L{l}")
            print(f"    column: {c}")
            print(f"    level: {l}")
            print(f"    tag_id: {COL_TAG[c]}")
            print(f"    bin_pose:      {{x: {x:.2f}, y: {RACK_FACE_Y:.2f}, z: {z:.2f}}}        # label centre on the rack face")
            print(f"    standoff_pose: {{x: {x:.2f}, y: 0.00, z: {z:.2f}, yaw: {STANDOFF_YAW}}}  # drone pose to read it")
            print(f"    sap_slot: RACK-A/{c:02d}/{l:02d}")


if __name__ == "__main__":
    main()
